/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_commonsware_cwac_anddown_AndDown */

#ifndef _Included_com_commonsware_cwac_anddown_AndDown
#define _Included_com_commonsware_cwac_anddown_AndDown
#ifdef __cplusplus
extern "C" {
#endif
#undef com_commonsware_cwac_anddown_AndDown_EMPTY_MARKDOWN_EXTENSIONS
#define com_commonsware_cwac_anddown_AndDown_EMPTY_MARKDOWN_EXTENSIONS 0L
/*
 * Class:     com_commonsware_cwac_anddown_AndDown
 * Method:    markdownToHtml
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_commonsware_cwac_anddown_AndDown_markdownToHtml
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
